# Generated by Django 6.0.5 on 2026-07-29 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_promo', models.CharField(help_text='Ej. Promo 2x1 Coca-Cola', max_length=100)),
                ('porcentaje_descuento', models.IntegerField(help_text='Ej. 10 para 10% de descuento')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
                ('producto_en_promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
