# Generated by Django 6.0.5 on 2026-07-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
