# Generated by Django 6.0.5 on 2026-07-29 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_sucursal_inventario'),
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.sucursal'),
        ),
    ]
